### ISSUE TITLE
Alerts.in.ua Private API

### ISSUE THREAD

**Issue by alerts-ua** [andrewyazura/brobots-air-raid-alerts#1]
Hi,
We noticed you're using a private API  version 2 of alerts.in.ua that could change or stop working anytime.
To avoid these issues, please contact us at api@alerts.in.ua to get an official API token.

**Comment by andrewyazura** [comment]
Fixed in c90e3d75cc3f7489f734591cc8716fd372f2a93d, thanks for the warning!
